# Generated by Django 5.0.1 on 2024-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jduuser',
            old_name='prents_phone_num',
            new_name='parents_phone_num',
        ),
        migrations.AddField(
            model_name='jduuser',
            name='quote',
            field=models.CharField(choices=[('cont', 'Shartnoma asosida'), ('grnt', 'Budjet asosida'), ('faiL', 'Qabul qilinmadingiz')], default='cont', max_length=4),
        ),
    ]
