# Generated by Django 5.0.1 on 2024-01-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_prents_phone_num_jduuser_parents_phone_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jduuser',
            old_name='parents_phone_num',
            new_name='prents_phone_num',
        ),
    ]
