# Generated by Django 5.0.1 on 2024-01-23 09:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_prents_phone_num_jduuser_parents_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jduuser',
            name='parents_phone_num',
        ),
        migrations.AddField(
            model_name='jduuser',
            name='prents_phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
